### PR TITLE
Hi I am Amrit

### PR DESCRIPTION
**Pull request by solo-daemon**
So basically I have squashed the commits into one and I they are now acceptable to be merged

### CODE REVIEW

**Comment by ayu023ban** [comment]
you should never make pull requests from master branch.

**Comment by ayu023ban** [comment]
Moreover please be a little more descriptive in your commit message.
Your file changes also includes merge arrows (see file changes for reference). you have to correct them.

**Comment by solo-daemon** [comment]
So in this I solved the arrow issue and I will take care of the description of commit and will make pull request from main branch only

**Comment by ayu023ban** [comment]
You should not make PR from both main and master branch. You should make a third branch whose name is related to what you are working on (like "add-amrit-name").

Also you have to combine the 3 commits into one single commit and then update this PR.
One more thing, don't close this PR and make a new one. Instead try to correct this PR.

**Pull request merged**
