### PR TITLE
Vaishnavi's GitHub assignment

### PR DESCRIPTION
**Pull request by DaveVaishnavi**

### CODE REVIEW

**Comment by ShreyasTheOne** [comment]
Please rename your pull request with a fitting message! 'Assignment' is very vague. It must include your name at least

**Comment by ayu023ban** [comment]
This PR is showing 4 commits. There should be ideally only one commit showing your work. please resolve this issue.

**Comment by DaveVaishnavi** [comment]
I actually made a mistake in the first commit. Should I create a new
repository ?

**Comment by ShreyasTheOne** [comment]
@DaveVaishnavi there are ways to keep using the same repository. Please try to find a solution :)

**Pull request closed without merging**
